version: "3.6"
services:

  mb:
    build: .
    ports:
    - '2525:2525'
    - '8090:8090'  
    - '42000:42000'
    volumes:
    - ./imposters:/imposters
    command: mb --configfile /imposters/imposters.ejs --allowInjection
